(()=>{
'use strict';
const frame=document.getElementById('game'); if(!frame)return;
const THEME_KEY='museumThemeV1', TOUR_KEY='museumOnboardingV1';
let theme=localStorage.getItem(THEME_KEY)||'dark', tour=null, step=0;
const css=document.createElement('style');css.textContent=`
:root{--guide-red:#e53935}html[data-theme="light"] body{background:#eee9df!important}.game-tools{position:fixed;top:54px;right:18px;z-index:1200;display:flex;gap:6px}.game-tool{border:1px solid #6e6244;background:rgba(13,17,16,.96);color:#f2efe7;padding:7px 10px;border-radius:6px;cursor:pointer;font:600 .78rem "Segoe UI",Tahoma,Arial,sans-serif;box-shadow:0 7px 24px rgba(0,0,0,.22)}html[data-theme="light"] .game-tool{background:#fffaf1;color:#252925;border-color:#9d8960}.tour-target-parent{outline:4px solid var(--guide-red)!important;outline-offset:4px!important;box-shadow:0 0 0 7px rgba(229,57,53,.18)!important}.tour-box{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:1400;width:min(520px,calc(100vw - 24px));background:#151918;color:#f7f2e8;border:2px solid var(--guide-red);border-radius:10px;padding:14px 15px;box-shadow:0 18px 60px rgba(0,0,0,.46);font-family:"Segoe UI",Tahoma,Arial,sans-serif}.tour-box strong{display:block;color:#ff9b98;margin-bottom:5px}.tour-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:10px}.tour-actions button{border:1px solid #777;background:#252b29;color:#fff;padding:6px 10px;border-radius:5px;cursor:pointer}.tour-actions .next{border-color:#ff6b67;color:#fff}.tour-count{float:left;color:#aaa;font-size:.75rem;margin-top:8px}html[data-theme="light"] .qr-card{background:rgba(255,250,241,.97)!important;color:#252925!important;border-color:#9d8960!important}html[data-theme="light"] .qr-card span{color:#5c635d!important}@media(max-width:850px){.game-tools{top:8px;right:8px}.game-tool{padding:6px 8px;font-size:.72rem}.tour-box{bottom:78px}}
`;document.head.appendChild(css);
const tools=document.createElement('div');tools.className='game-tools';tools.id='gameTools';tools.innerHTML='<button class="game-tool" id="tourBtn" type="button">? Οδηγός</button><button class="game-tool" id="themeBtn" type="button"></button>';document.body.appendChild(tools);
const themeBtn=document.getElementById('themeBtn');
function lightInnerCSS(){return `
html[data-game-theme="light"],html[data-game-theme="light"] body{background:#f1ede4!important;color:#202521!important;color-scheme:light!important}html[data-game-theme="light"]{--bg:#f1ede4;--panel:#faf7f0;--panel2:#fffdf8;--ink:#202521;--muted:#626a64;--line:#b8b0a2;--gold:#8a6522;--gold2:#684b16;--shadow:0 14px 42px rgba(80,65,35,.14)}html[data-game-theme="light"] .topbar,html[data-game-theme="light"] .controls{background:#e8e1d4!important;color:#4e5650!important}html[data-game-theme="light"] .card,html[data-game-theme="light"] .content,html[data-game-theme="light"] .voicepane,html[data-game-theme="light"] .strategy,html[data-game-theme="light"] .score,html[data-game-theme="light"] .team-screen,html[data-game-theme="light"] .exhibit-review,html[data-game-theme="light"] .debrief,html[data-game-theme="light"] .panel,html[data-game-theme="light"] .person,html[data-game-theme="light"] .modalbox{background:#faf7f0!important;color:#202521!important;border-color:#b8b0a2!important}html[data-game-theme="light"] .hero{background:linear-gradient(145deg,#fffdf8,#eee8dd)!important}html[data-game-theme="light"] .bodycopy,html[data-game-theme="light"] .subtitle,html[data-game-theme="light"] .manifesto,html[data-game-theme="light"] .hero p,html[data-game-theme="light"] .panel p,html[data-game-theme="light"] .voicehint{color:#343a36!important}html[data-game-theme="light"] .option{background:#fffdf8!important;color:#202521!important;border-color:#aaa294!important}html[data-game-theme="light"] .note,html[data-game-theme="light"] .mini,html[data-game-theme="light"] .scorecard{background:#eee9df!important;color:#303632!important;border-color:#b8b0a2!important}html[data-game-theme="light"] .meta,html[data-game-theme="light"] .option small,html[data-game-theme="light"] .person p{color:#646c66!important}
.action-required,.tour-target-inner{outline:4px solid #e53935!important;outline-offset:3px!important;border-color:#e53935!important;box-shadow:0 0 0 7px rgba(229,57,53,.18),0 0 20px rgba(229,57,53,.35)!important;animation:guidePulse 1.25s ease-in-out infinite!important}.startprompt.action-required{color:#ff7772!important;border-color:#e53935!important}.controls .action-required{padding:4px 7px!important;border-radius:5px!important;background:rgba(229,57,53,.12)!important}@keyframes guidePulse{50%{box-shadow:0 0 0 3px rgba(229,57,53,.12),0 0 8px rgba(229,57,53,.22)}}`}
function ensureInner(d){let s=d.getElementById('museum-interaction-layer');if(!s){s=d.createElement('style');s.id='museum-interaction-layer';s.textContent=lightInnerCSS();d.head.appendChild(s)}d.documentElement.dataset.gameTheme=theme;markAction(d);const stage=d.getElementById('stage');if(stage&&!stage.__guideObserver){stage.__guideObserver=new MutationObserver(()=>{markAction(d);if(tour)refreshTourTarget()});stage.__guideObserver.observe(stage,{childList:true,subtree:true,attributes:true,attributeFilter:['class']})}}
function markAction(d){d.querySelectorAll('.action-required').forEach(x=>x.classList.remove('action-required'));let t=d.querySelector('.startprompt')||d.querySelector('.option.focused');if(!t&&d.querySelector('.dialogue')){t=[...d.querySelectorAll('.controls>span')].find(x=>/A\s*\/\s*Enter/i.test(x.textContent))}if(t)t.classList.add('action-required')}
function applyTheme(){document.documentElement.dataset.theme=theme;themeBtn.textContent=theme==='dark'?'☀ Φωτεινό':'☾ Σκοτεινό';themeBtn.title=theme==='dark'?'Μετάβαση σε φωτεινό θέμα':'Μετάβαση σε σκοτεινό θέμα';try{ensureInner(frame.contentDocument)}catch(e){}}
themeBtn.onclick=()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem(THEME_KEY,theme);applyTheme()};
function clearTargets(){document.querySelectorAll('.tour-target-parent').forEach(x=>x.classList.remove('tour-target-parent'));try{frame.contentDocument.querySelectorAll('.tour-target-inner').forEach(x=>x.classList.remove('tour-target-inner'))}catch(e){}}
function targetFor(s){if(s.where==='parent')return document.querySelector(s.sel);try{return frame.contentDocument.querySelector(s.sel)}catch(e){return null}}
function refreshTourTarget(){if(!tour)return;clearTargets();const s=tour[step],t=targetFor(s);if(t)t.classList.add(s.where==='parent'?'tour-target-parent':'tour-target-inner')}
function tourSteps(){const mobile=document.getElementById('touchbar');const arr=[{where:'inner',sel:'.startprompt',title:'Ξεκίνα από εδώ',text:'Το κόκκινο στοιχείο είναι αυτό που περιμένει ενέργεια. Πάτησε Enter/A ή «Επιλογή» στο κινητό.'},{where:mobile?'parent':'inner',sel:mobile?'#touchbar':'.controls',title:'Χειρισμός',text:'Με τα βελάκια αλλάζεις επιλογή. Enter/A επιβεβαιώνει, Y ανοίγει βοήθεια και Esc/B επιστρέφει.'},{where:'parent',sel:'#gameTools',title:'Οδηγός και εμφάνιση',text:'Από εδώ μπορείς οποιαδήποτε στιγμή να ξαναδείς τον οδηγό ή να αλλάξεις μεταξύ φωτεινού και σκοτεινού θέματος.'}];const q=document.getElementById('mobileQR');if(q&&getComputedStyle(q).display!=='none')arr.push({where:'parent',sel:'#mobileQR',title:'Συνέχισε στο κινητό',text:'Το QR ανοίγει την ειδική έκδοση αφής του παιχνιδιού.'});return arr}
function showStep(){if(!tour)return;refreshTourTarget();let box=document.getElementById('tourBox');if(!box){box=document.createElement('div');box.id='tourBox';box.className='tour-box';document.body.appendChild(box)}const s=tour[step];box.innerHTML=`<strong>${s.title}</strong><div>${s.text}</div><span class="tour-count">${step+1} / ${tour.length}</span><div class="tour-actions"><button id="tourSkip">Παράλειψη</button><button class="next" id="tourNext">${step===tour.length-1?'Τέλος':'Επόμενο'}</button></div>`;document.getElementById('tourSkip').onclick=endTour;document.getElementById('tourNext').onclick=()=>{if(step<tour.length-1){step++;showStep()}else endTour()}}
function startTour(){tour=tourSteps();step=0;showStep()}
function endTour(){clearTargets();document.getElementById('tourBox')?.remove();tour=null;localStorage.setItem(TOUR_KEY,'1')}
document.getElementById('tourBtn').onclick=startTour;
frame.addEventListener('load',()=>{try{ensureInner(frame.contentDocument);applyTheme();setTimeout(()=>{if(!localStorage.getItem(TOUR_KEY))startTour()},500)}catch(e){console.error(e)}});
applyTheme();
})();